// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	TransactionID string             `json:"transaction_id"`
	PayerVpa      string             `json:"payer_vpa"`
	PayeeVpa      string             `json:"payee_vpa"`
	Amount        int64              `json:"amount"`
	Status        string             `json:"status"`
	BankRefID     pgtype.Text        `json:"bank_ref_id"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	Remarks       pgtype.Text        `json:"remarks"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
