// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetTransactionHistory(ctx context.Context, arg GetTransactionHistoryParams) ([]Transaction, error)
}

var _ Querier = (*Queries)(nil)
