// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: txn_queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    transaction_id,
    payer_vpa,
    payee_vpa,
    amount,
    remarks
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING transaction_id, payer_vpa, payee_vpa, amount, status, bank_ref_id, failure_reason, remarks, created_at, updated_at
`

type CreateTransactionParams struct {
	TransactionID string      `json:"transaction_id"`
	PayerVpa      string      `json:"payer_vpa"`
	PayeeVpa      string      `json:"payee_vpa"`
	Amount        int64       `json:"amount"`
	Remarks       pgtype.Text `json:"remarks"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.TransactionID,
		arg.PayerVpa,
		arg.PayeeVpa,
		arg.Amount,
		arg.Remarks,
	)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.PayerVpa,
		&i.PayeeVpa,
		&i.Amount,
		&i.Status,
		&i.BankRefID,
		&i.FailureReason,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionHistory = `-- name: GetTransactionHistory :many
SELECT 
    transaction_id,
    payer_vpa,
    payee_vpa,
    amount,
    status,
    bank_ref_id,
    failure_reason,
    remarks,
    created_at,
    updated_at
FROM transactions
WHERE payer_vpa = $1 OR payee_vpa = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionHistoryParams struct {
	PayerVpa string `json:"payer_vpa"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetTransactionHistory(ctx context.Context, arg GetTransactionHistoryParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionHistory, arg.PayerVpa, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TransactionID,
			&i.PayerVpa,
			&i.PayeeVpa,
			&i.Amount,
			&i.Status,
			&i.BankRefID,
			&i.FailureReason,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
